data_dir: /bess23/huaize/SITS-MoCo/data/s1  # where the data is donwwloaded
satellite_default:
  resolution: 30
  tile_size: 5_000  # the side length, in pixel, of downloaded rasters
  dtype: Float32
  composite_method: MEDIAN  # see geefetch.enums.CompositeMethod
  aoi:
    spatial:
      left: 0
      right: 1
      bottom: 0
      top: 1
      epsg: 4326  # the CRS in which the AOI is expressed
    temporal:
      start_date: 2020-01-01
      end_date: 2020-01-02
  gee:
    ee_project_id: ee-project-id # add your Earth Engine project id here.
    max_tile_size: 8 # in MB, decrease if User Memory Excess Error, choose highest possible otherwise.
s1:
  composite_method: MEAN
s2: {} # use satellite_default
dynworld:
  composite_method: ${s1.composite_method}